#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCrossUtilities.Samples.AllAround.Droid.Resource", IsApplication=true)]

namespace MvvmCrossUtilities.Samples.AllAround.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.collapsed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.collapsed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.divider = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.divider;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.expanded = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.expanded;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_disabled = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_disabled;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_focus = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_focus;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_longpress = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_longpress;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_pressed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_pressed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_transition = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_transition;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.dialogTitle = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.dialogTitle;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.tree_list_item_multi_selector = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.tree_list_item_multi_selector;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.treeview_list_item_frame = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.treeview_list_item_frame;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.treeview_list_item_image = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.treeview_list_item_image;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.treeview_list_item_image_layout = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.treeview_list_item_image_layout;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Layout.Dialog_Common_TitleMultiline = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Layout.Dialog_Common_TitleMultiline;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Layout.tree_list_item_wrapper = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Layout.tree_list_item_wrapper;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.ApplicationName = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.ApplicationName;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.Hello = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.Hello;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.app_name = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.app_name;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapse_all_condesed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapse_all_condesed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapse_all_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapse_all_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_condensed_disable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_condensed_disable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_condensed_enable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_condensed_enable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_menu_disable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_menu_disable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_menu_enable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_menu_enable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.delete_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.delete_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.delete_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.delete_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_all_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_all_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_all_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_all_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.fancy_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.fancy_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.fancy_menu_name = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.fancy_menu_name;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.simple_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.simple_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.simple_menu_name = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.simple_menu_name;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Style.treeViewListStyle = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Style.treeViewListStyle;
			global::MvvmCrossUtilities.Plugins.Device.Droid.Resource.Raw.FourBeeps = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Raw.FourBeeps;
			global::MvvmCrossUtilities.Plugins.Device.Droid.Resource.Raw.OneBeep = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Raw.OneBeep;
			global::MvvmCrossUtilities.Plugins.Device.Droid.Resource.Raw.TwoBeeps = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Raw.TwoBeeps;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010020
			public const int GroupItemTemplate = 2130772000;
			
			// aapt resource value: 0x7f01001b
			public const int MvxBind = 2130771995;
			
			// aapt resource value: 0x7f01001f
			public const int MvxDropDownItemTemplate = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int MvxItemTemplate = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public const int MvxLang = 2130771996;
			
			// aapt resource value: 0x7f010021
			public const int MvxSource = 2130772001;
			
			// aapt resource value: 0x7f01001d
			public const int MvxTemplate = 2130771997;
			
			// aapt resource value: 0x7f010019
			public const int click_remove_id = 2130771993;
			
			// aapt resource value: 0x7f010009
			public const int collapsed_height = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int collapsible = 2130771969;
			
			// aapt resource value: 0x7f010013
			public const int drag_enabled = 2130771987;
			
			// aapt resource value: 0x7f010017
			public const int drag_handle_id = 2130771991;
			
			// aapt resource value: 0x7f01000a
			public const int drag_scroll_start = 2130771978;
			
			// aapt resource value: 0x7f010016
			public const int drag_start_mode = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int drop_animation_duration = 2130771986;
			
			// aapt resource value: 0x7f010018
			public const int fling_handle_id = 2130771992;
			
			// aapt resource value: 0x7f01000f
			public const int float_alpha = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int float_background_color = 2130771980;
			
			// aapt resource value: 0x7f010005
			public const int handle_trackball_press = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int indent_width = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int indicator_background = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int indicator_gravity = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int max_drag_scroll_speed = 2130771979;
			
			// aapt resource value: 0x7f010011
			public const int remove_animation_duration = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int remove_enabled = 2130771989;
			
			// aapt resource value: 0x7f01000d
			public const int remove_mode = 2130771981;
			
			// aapt resource value: 0x7f010008
			public const int row_background = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int selection_enabled = 2130771968;
			
			// aapt resource value: 0x7f010010
			public const int slide_shuffle_speed = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int sort_enabled = 2130771988;
			
			// aapt resource value: 0x7f010003
			public const int src_collapsed = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int src_expanded = 2130771970;
			
			// aapt resource value: 0x7f01000e
			public const int track_drag_sort = 2130771982;
			
			// aapt resource value: 0x7f01001a
			public const int use_default_controller = 2130771994;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int collapsed = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int expanded = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_not_visible = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_visible = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int list_selector_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list_selector_background_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int list_selector_background_focus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int list_selector_background_longpress = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int list_selector_background_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int list_selector_background_transition = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int CustomEditTextPageHeader = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int DecimalEditTextEditControl = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int DecimalEditTextReadonlyControl = 2131165207;
			
			// aapt resource value: 0x7f07001e
			public const int DeviceButtonsLayout = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int DevicePageHeader = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int LinearLayoutTitleDecimalEditText = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int LinearLayoutTitleNumericEditText = 2131165209;
			
			// aapt resource value: 0x7f070000
			public const int MvxBindingTagUnique = 2131165184;
			
			// aapt resource value: 0x7f07001a
			public const int NumericEditTextEditControl = 2131165210;
			
			// aapt resource value: 0x7f070018
			public const int NumericEditTextMaxDecimalPlaces = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int NumericEditTextReadonlyControl = 2131165211;
			
			// aapt resource value: 0x7f070001
			public const int bottom = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int center = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int center_horizontal = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int center_vertical = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int clickRemove = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int clip_horizontal = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int clip_vertical = 2131165190;
			
			// aapt resource value: 0x7f070012
			public const int dialogTitle = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int drag_handle = 2131165203;
			
			// aapt resource value: 0x7f070007
			public const int fill = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int fill_horizontal = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int fill_vertical = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int flingRemove = 2131165198;
			
			// aapt resource value: 0x7f070023
			public const int itemsList = 2131165219;
			
			// aapt resource value: 0x7f07000a
			public const int left = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int onDown = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int onLongPress = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int onMove = 2131165201;
			
			// aapt resource value: 0x7f070020
			public const int pageButtonList1 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int pageButtonList2 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int pageButtonList3 = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int pageTitle = 2131165215;
			
			// aapt resource value: 0x7f07000b
			public const int right = 2131165195;
			
			// aapt resource value: 0x7f07001d
			public const int scrollView1 = 2131165213;
			
			// aapt resource value: 0x7f070024
			public const int selectedItemsLabel = 2131165220;
			
			// aapt resource value: 0x7f07000c
			public const int top = 2131165196;
			
			// aapt resource value: 0x7f070029
			public const int tree_list_item_multi_selector = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int treeview_list_item_frame = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int treeview_list_item_image = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int treeview_list_item_image_layout = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int viewTitle = 2131165221;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialog_Common_TitleMultiline = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GroupItem_User = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListItem_Color = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItem_MenuOption = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListItem_ReadOnlyItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListItem_SelectableItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Page_ColorView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Page_ContextOptionsView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Page_CustomEditTextView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Page_DeviceView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Page_DialogView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Page_DragAndDropListView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Page_ListView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Page_LoggerView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Page_MainView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Page_NotificationsView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Page_RestServicesView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Page_TreeViewListView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Page_ViewPagerView = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int PageCommon_Titlebar = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SplashScreen = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int tree_list_item_wrapper = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ViewPagerItem_ChildViewTemplate = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int FourBeeps = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int OneBeep = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int TwoBeeps = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int collapse_all_condesed = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int collapse_all_menu = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int collapsible_condensed_disable = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int collapsible_condensed_enable = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int collapsible_menu_disable = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int collapsible_menu_enable = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int delete_menu = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int delete_menu_condensed = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int expand_all_condensed = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int expand_all_menu = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int expand_menu = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int expand_menu_condensed = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int fancy_menu_condensed = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int fancy_menu_name = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int simple_menu_condensed = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int simple_menu_name = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int treeViewListStyle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] BindableDragSortListView = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 16
			public const int BindableDragSortListView_click_remove_id = 16;
			
			// aapt resource value: 0
			public const int BindableDragSortListView_collapsed_height = 0;
			
			// aapt resource value: 10
			public const int BindableDragSortListView_drag_enabled = 10;
			
			// aapt resource value: 14
			public const int BindableDragSortListView_drag_handle_id = 14;
			
			// aapt resource value: 1
			public const int BindableDragSortListView_drag_scroll_start = 1;
			
			// aapt resource value: 13
			public const int BindableDragSortListView_drag_start_mode = 13;
			
			// aapt resource value: 9
			public const int BindableDragSortListView_drop_animation_duration = 9;
			
			// aapt resource value: 15
			public const int BindableDragSortListView_fling_handle_id = 15;
			
			// aapt resource value: 6
			public const int BindableDragSortListView_float_alpha = 6;
			
			// aapt resource value: 3
			public const int BindableDragSortListView_float_background_color = 3;
			
			// aapt resource value: 2
			public const int BindableDragSortListView_max_drag_scroll_speed = 2;
			
			// aapt resource value: 8
			public const int BindableDragSortListView_remove_animation_duration = 8;
			
			// aapt resource value: 12
			public const int BindableDragSortListView_remove_enabled = 12;
			
			// aapt resource value: 4
			public const int BindableDragSortListView_remove_mode = 4;
			
			// aapt resource value: 7
			public const int BindableDragSortListView_slide_shuffle_speed = 7;
			
			// aapt resource value: 11
			public const int BindableDragSortListView_sort_enabled = 11;
			
			// aapt resource value: 5
			public const int BindableDragSortListView_track_drag_sort = 5;
			
			// aapt resource value: 17
			public const int BindableDragSortListView_use_default_controller = 17;
			
			public static int[] BindableTreeViewList = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int BindableTreeViewList_collapsible = 1;
			
			// aapt resource value: 5
			public const int BindableTreeViewList_handle_trackball_press = 5;
			
			// aapt resource value: 4
			public const int BindableTreeViewList_indent_width = 4;
			
			// aapt resource value: 7
			public const int BindableTreeViewList_indicator_background = 7;
			
			// aapt resource value: 6
			public const int BindableTreeViewList_indicator_gravity = 6;
			
			// aapt resource value: 8
			public const int BindableTreeViewList_row_background = 8;
			
			// aapt resource value: 0
			public const int BindableTreeViewList_selection_enabled = 0;
			
			// aapt resource value: 3
			public const int BindableTreeViewList_src_collapsed = 3;
			
			// aapt resource value: 2
			public const int BindableTreeViewList_src_expanded = 2;
			
			public static int[] MvxBinding = new int[] {
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771997};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130772000};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_GroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772001};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771998,
					2130771999};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
