#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCrossUtilities.Samples.AllAround.Droid.Resource", IsApplication=true)]

namespace MvvmCrossUtilities.Samples.AllAround.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.collapsible = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.collapsible;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.handle_trackball_press = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.handle_trackball_press;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.indent_width = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.indent_width;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.indicator_background = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.indicator_background;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.indicator_gravity = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.indicator_gravity;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.row_background = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.row_background;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.src_collapsed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.src_collapsed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Attribute.src_expanded = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Attribute.src_expanded;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.collapsed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.collapsed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.divider = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.divider;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.expanded = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.expanded;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_disabled = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_disabled;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_focus = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_focus;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_longpress = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_longpress;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_pressed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_pressed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Drawable.list_selector_background_transition = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Drawable.list_selector_background_transition;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.bottom = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.bottom;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.center = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.center;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.center_horizontal = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.center_horizontal;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.center_vertical = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.center_vertical;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.clip_horizontal = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.clip_horizontal;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.clip_vertical = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.clip_vertical;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.dialogTitle = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.dialogTitle;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.fill = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.fill;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.fill_horizontal = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.fill_horizontal;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.fill_vertical = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.fill_vertical;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.left = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.left;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.right = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.right;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.top = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.top;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.tree_list_item_multi_selector = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.tree_list_item_multi_selector;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.treeview_list_item_frame = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.treeview_list_item_frame;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.treeview_list_item_image = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.treeview_list_item_image;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Id.treeview_list_item_image_layout = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Id.treeview_list_item_image_layout;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Layout.Dialog_Common_TitleMultiline = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Layout.Dialog_Common_TitleMultiline;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Layout.tree_list_item_wrapper = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Layout.tree_list_item_wrapper;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.app_name = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.app_name;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapse_all_condesed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapse_all_condesed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapse_all_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapse_all_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_condensed_disable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_condensed_disable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_condensed_enable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_condensed_enable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_menu_disable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_menu_disable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.collapsible_menu_enable = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.collapsible_menu_enable;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.delete_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.delete_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.delete_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.delete_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_all_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_all_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_all_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_all_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_menu = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_menu;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.expand_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.expand_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.fancy_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.fancy_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.fancy_menu_name = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.fancy_menu_name;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.simple_menu_condensed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.simple_menu_condensed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.String.simple_menu_name = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.String.simple_menu_name;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Style.treeViewListStyle = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Style.treeViewListStyle;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_collapsible = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_collapsible;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_handle_trackball_press = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_handle_trackball_press;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_indent_width = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_indent_width;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_indicator_background = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_indicator_background;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_indicator_gravity = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_indicator_gravity;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_row_background = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_row_background;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_src_collapsed = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_src_collapsed;
			global::MvvmCrossUtilities.Libraries.Droid.Resource.Styleable.TreeViewList_src_expanded = global::MvvmCrossUtilities.Samples.AllAround.Droid.Resource.Styleable.TreeViewList_src_expanded;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010008
			public const int MvxBind = 2130771976;
			
			// aapt resource value: 0x7f01000c
			public const int MvxDropDownItemTemplate = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int MvxItemTemplate = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int MvxLang = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public const int MvxSource = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int MvxTemplate = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int collapsible = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int handle_trackball_press = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int indent_width = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int indicator_background = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int indicator_gravity = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int row_background = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int src_collapsed = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int src_expanded = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int collapsed = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int expanded = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int list_selector_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int list_selector_background_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int list_selector_background_focus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list_selector_background_longpress = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int list_selector_background_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int list_selector_background_transition = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040010
			public const int DeviceButtonsLayout = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int DevicePageHeader = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int MvxBindingTagUnique = 2130968588;
			
			// aapt resource value: 0x7f040001
			public const int bottom = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int center = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int center_horizontal = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int center_vertical = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int clip_horizontal = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int clip_vertical = 2130968586;
			
			// aapt resource value: 0x7f04000d
			public const int dialogTitle = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int fill = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int fill_horizontal = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int fill_vertical = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int itemsList = 2130968597;
			
			// aapt resource value: 0x7f040002
			public const int left = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int pageButtonList1 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int pageButtonList2 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int pageButtonList3 = 2130968596;
			
			// aapt resource value: 0x7f040011
			public const int pageTitle = 2130968593;
			
			// aapt resource value: 0x7f040003
			public const int right = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int scrollView1 = 2130968591;
			
			// aapt resource value: 0x7f040016
			public const int selectedItemsLabel = 2130968598;
			
			// aapt resource value: 0x7f040000
			public const int top = 2130968576;
			
			// aapt resource value: 0x7f04001b
			public const int tree_list_item_multi_selector = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int treeview_list_item_frame = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int treeview_list_item_image = 2130968601;
			
			// aapt resource value: 0x7f040018
			public const int treeview_list_item_image_layout = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int viewTitle = 2130968599;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialog_Common_TitleMultiline = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int GroupItem_User = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListItem_Articles = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListItem_Color = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListItem_MenuOption = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListItem_ReadOnlyItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListItem_SelectableItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Page_ArticlesView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Page_ColorView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Page_DeviceView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Page_DialogView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Page_ListView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Page_LoggerView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Page_MainView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Page_RestServicesView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Page_TreeViewListView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Page_ViewPagerView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PageCommon_Titlebar = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SplashScreen = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int tree_list_item_wrapper = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ViewPagerItem_ChildViewTemplate = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int ApplicationName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int Hello = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int collapse_all_condesed = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int collapse_all_menu = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int collapsible_condensed_disable = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int collapsible_condensed_enable = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int collapsible_menu_disable = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int collapsible_menu_enable = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int delete_menu = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int delete_menu_condensed = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int expand_all_condensed = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int expand_all_menu = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int expand_menu = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int expand_menu_condensed = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int fancy_menu_condensed = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int fancy_menu_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int simple_menu_condensed = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int simple_menu_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int treeViewListStyle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771981};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] TreeViewList = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int TreeViewList_collapsible = 0;
			
			// aapt resource value: 4
			public const int TreeViewList_handle_trackball_press = 4;
			
			// aapt resource value: 3
			public const int TreeViewList_indent_width = 3;
			
			// aapt resource value: 6
			public const int TreeViewList_indicator_background = 6;
			
			// aapt resource value: 5
			public const int TreeViewList_indicator_gravity = 5;
			
			// aapt resource value: 7
			public const int TreeViewList_row_background = 7;
			
			// aapt resource value: 2
			public const int TreeViewList_src_collapsed = 2;
			
			// aapt resource value: 1
			public const int TreeViewList_src_expanded = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
