#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCrossUtilities.Libraries.Droid.Resource", IsApplication=false)]

namespace MvvmCrossUtilities.Libraries.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int collapsed = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int expanded = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int list_selector_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int list_selector_background_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int list_selector_background_focus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int list_selector_background_longpress = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int list_selector_background_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int list_selector_background_transition = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int dialogTitle = 2131099648;
			
			// aapt resource value: 0x7f060004
			public static int tree_list_item_multi_selector = 2131099652;
			
			// aapt resource value: 0x7f060003
			public static int treeview_list_item_frame = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int treeview_list_item_image = 2131099650;
			
			// aapt resource value: 0x7f060001
			public static int treeview_list_item_image_layout = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int Dialog_Common_TitleMultiline = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int tree_list_item_wrapper = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public static int app_name = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public static int collapse_all_condesed = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public static int collapse_all_menu = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public static int collapsible_condensed_disable = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public static int collapsible_condensed_enable = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int collapsible_menu_disable = 2130968587;
			
			// aapt resource value: 0x7f040009
			public static int collapsible_menu_enable = 2130968585;
			
			// aapt resource value: 0x7f040011
			public static int delete_menu = 2130968593;
			
			// aapt resource value: 0x7f040012
			public static int delete_menu_condensed = 2130968594;
			
			// aapt resource value: 0x7f040008
			public static int expand_all_condensed = 2130968584;
			
			// aapt resource value: 0x7f040007
			public static int expand_all_menu = 2130968583;
			
			// aapt resource value: 0x7f04000f
			public static int expand_menu = 2130968591;
			
			// aapt resource value: 0x7f040010
			public static int expand_menu_condensed = 2130968592;
			
			// aapt resource value: 0x7f040006
			public static int fancy_menu_condensed = 2130968582;
			
			// aapt resource value: 0x7f040005
			public static int fancy_menu_name = 2130968581;
			
			// aapt resource value: 0x7f040004
			public static int simple_menu_condensed = 2130968580;
			
			// aapt resource value: 0x7f040003
			public static int simple_menu_name = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public static int treeViewListStyle = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
