#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCrossUtilities.Libraries.Droid.Resource", IsApplication=false)]

namespace MvvmCrossUtilities.Libraries.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int collapsible = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int handle_trackball_press = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int indent_width = 2130771971;
			
			// aapt resource value: 0x7f010006
			public static int indicator_background = 2130771974;
			
			// aapt resource value: 0x7f010005
			public static int indicator_gravity = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int row_background = 2130771975;
			
			// aapt resource value: 0x7f010002
			public static int src_collapsed = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int src_expanded = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int collapsed = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int expanded = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int list_selector_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int list_selector_background_disabled = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int list_selector_background_focus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int list_selector_background_longpress = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int list_selector_background_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int list_selector_background_transition = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public static int bottom = 2130968577;
			
			// aapt resource value: 0x7f040008
			public static int center = 2130968584;
			
			// aapt resource value: 0x7f040006
			public static int center_horizontal = 2130968582;
			
			// aapt resource value: 0x7f040004
			public static int center_vertical = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public static int clip_horizontal = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public static int clip_vertical = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public static int dialogTitle = 2130968588;
			
			// aapt resource value: 0x7f040009
			public static int fill = 2130968585;
			
			// aapt resource value: 0x7f040007
			public static int fill_horizontal = 2130968583;
			
			// aapt resource value: 0x7f040005
			public static int fill_vertical = 2130968581;
			
			// aapt resource value: 0x7f040002
			public static int left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int right = 2130968579;
			
			// aapt resource value: 0x7f040000
			public static int top = 2130968576;
			
			// aapt resource value: 0x7f040010
			public static int tree_list_item_multi_selector = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public static int treeview_list_item_frame = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public static int treeview_list_item_image = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public static int treeview_list_item_image_layout = 2130968589;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int Dialog_Common_TitleMultiline = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int tree_list_item_wrapper = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public static int collapse_all_condesed = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public static int collapse_all_menu = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public static int collapsible_condensed_disable = 2131034122;
			
			// aapt resource value: 0x7f050008
			public static int collapsible_condensed_enable = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int collapsible_menu_disable = 2131034121;
			
			// aapt resource value: 0x7f050007
			public static int collapsible_menu_enable = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public static int delete_menu = 2131034127;
			
			// aapt resource value: 0x7f050010
			public static int delete_menu_condensed = 2131034128;
			
			// aapt resource value: 0x7f050006
			public static int expand_all_condensed = 2131034118;
			
			// aapt resource value: 0x7f050005
			public static int expand_all_menu = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public static int expand_menu = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int expand_menu_condensed = 2131034126;
			
			// aapt resource value: 0x7f050004
			public static int fancy_menu_condensed = 2131034116;
			
			// aapt resource value: 0x7f050003
			public static int fancy_menu_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public static int simple_menu_condensed = 2131034114;
			
			// aapt resource value: 0x7f050001
			public static int simple_menu_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int treeViewListStyle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TreeViewList = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public static int TreeViewList_collapsible = 0;
			
			// aapt resource value: 4
			public static int TreeViewList_handle_trackball_press = 4;
			
			// aapt resource value: 3
			public static int TreeViewList_indent_width = 3;
			
			// aapt resource value: 6
			public static int TreeViewList_indicator_background = 6;
			
			// aapt resource value: 5
			public static int TreeViewList_indicator_gravity = 5;
			
			// aapt resource value: 7
			public static int TreeViewList_row_background = 7;
			
			// aapt resource value: 2
			public static int TreeViewList_src_collapsed = 2;
			
			// aapt resource value: 1
			public static int TreeViewList_src_expanded = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
