#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MvvmCrossUtilities.Plugins.Device.Droid.Resource", IsApplication=false)]

namespace MvvmCrossUtilities.Plugins.Device.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f020000
			public static int FourBeeps = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int OneBeep = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int TwoBeeps = 2130837506;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
	}
}
#pragma warning restore 1591
